### ISSUE TITLE
POD not starting in Centos 7 Kubernetes 1.8.4 cluster

### ISSUE THREAD

**Issue by grailsweb** [aledbf/kube-keepalived-vip#28]
Hi,
while creating the daemon set, pod is not starting, its crashing with this error message.

>  k logs kube-keepalived-vip-9sdg2
> ERROR: logging before flag.Parse: F1211 19:18:30.419110       1 main.go:105] unexpected error: exit status 1
>

here is pod log

```
 k describe pod kube-keepalived-vip-9sdg2
Name:           kube-keepalived-vip-9sdg2
Namespace:      default
Node:           k8s17-02/192.168.16.92
Start Time:     Mon, 11 Dec 2017 18:46:22 +0000
Labels:         controller-revision-hash=3248544204
                name=kube-keepalived-vip
                pod-template-generation=2
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"DaemonSet","namespace":"default","name":"kube-ke
epalived-vip","uid":"7930b6fb-dea3-11e7-a6ca-525400ada096"...
Status:         Running
IP:             192.168.16.92
Created By:     DaemonSet/kube-keepalived-vip
Controlled By:  DaemonSet/kube-keepalived-vip
Containers:
  kube-keepalived-vip:
    Container ID:  docker://38ba65ccc3db309883f76ac78c0998c191dfa2dcbfcfd57a1d3343c88dcbd983
    Image:         aledbf/kube-keepalived-vip:0.23
    Image ID:      docker-pullable://aledbf/kube-keepalived-vip@sha256:5fa8abf3ec60bdcb59921d472d4f6f022b715b34b8120ee175c764f710f1c8c0
    Port:          <none>
    Args:
      --services-configmap=default/vip-configmap
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Mon, 11 Dec 2017 19:18:30 +0000
      Finished:     Mon, 11 Dec 2017 19:18:30 +0000
 Ready:          False
    Restart Count:  11
    Environment:
      POD_NAME:       kube-keepalived-vip-9sdg2 (v1:metadata.name)
      POD_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /dev from dev (rw)
      /lib/modules from modules (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tnxvd (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  modules:
    Type:  HostPath (bare host directory volume)
    Path:  /lib/modules
  dev:
    Type:  HostPath (bare host directory volume)
    Path:  /dev
  default-token-tnxvd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-tnxvd
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute
                 node.alpha.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
Events:
  Type     Reason                 Age                 From               Message
  ----     ------                 ----                ----               -------
  Normal   SuccessfulMountVolume  36m                 kubelet, k8s17-02  MountVolume.SetUp succeeded for volume "dev"
  Normal   SuccessfulMountVolume  36m                 kubelet, k8s17-02  MountVolume.SetUp succeeded for volume "modules"
  Normal   SuccessfulMountVolume  36m                 kubelet, k8s17-02  MountVolume.SetUp succeeded for volume "default-token-tnxvd"
  Normal   Created                36m (x3 over 36m)   kubelet, k8s17-02  Created container
  Normal   Started                36m (x3 over 36m)   kubelet, k8s17-02  Started container
  Warning  BackOff                35m (x4 over 36m)   kubelet, k8s17-02  Back-off restarting failed container
  Normal   Pulling                35m (x4 over 36m)   kubelet, k8s17-02  pulling image "aledbf/kube-keepalived-vip:0.23"
  Normal   Pulled                 35m (x4 over 36m)   kubelet, k8s17-02  Successfully pulled image "aledbf/kube-keepalived-vip:0.23"
  Warning  FailedSync             1m (x155 over 36m)  kubelet, k8s17-02  Error syncing pod
 
```

**Comment by hoanhdo** [comment]
you should manually run command modprobe ip_vs and verify /proc/net/ip_vs exist.
hope this help.

**Comment by FNaughton** [comment]
I see the same. Have verified /proc/net/ip_vs exists as per @hoanhdo suggestion
```
[root@master1 ~]# cat /proc/net/ip_vs
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port Forward Weight ActiveConn InActConn

[root@master1 ~]# kubectl create -f vip-daemonset.yml
daemonset "kube-keepalived-vip" created

[root@master1 ~]# kubectl get po
NAME                                        READY     STATUS              RESTARTS   AGE
app1-7f545dcf86-c4ppb                       1/1       Running             1          8d
app1-7f545dcf86-xnlnp                       1/1       Running             1          8d
app1-7f545dcf86-zgqp2                       1/1       Running             2          8d
default-backend-78484f94cf-fv6v4            1/1       Running             2          27d
default-backend-78484f94cf-vzp8l            1/1       Running             1          27d
default-backend-78484f94cf-wmjqh            1/1       Running             1          27d
kube-keepalived-vip-hcw7x                   1/1       Running             0          5s
kube-keepalived-vip-m5zdk                   0/1       ContainerCreating   0          5s
kube-keepalived-vip-rkm7g                   0/1       ContainerCreating   0          5s
nginx-ingress-controller-57f899f46f-mwknf   1/1       Running             1          8d

[root@master1 ~]# kubectl get po
NAME                                        READY     STATUS             RESTARTS   AGE
app1-7f545dcf86-c4ppb                       1/1       Running            1          8d
app1-7f545dcf86-xnlnp                       1/1       Running            1          8d
app1-7f545dcf86-zgqp2                       1/1       Running            2          8d
default-backend-78484f94cf-fv6v4            1/1       Running            2          27d
default-backend-78484f94cf-vzp8l            1/1       Running            1          27d
default-backend-78484f94cf-wmjqh            1/1       Running            1          27d
kube-keepalived-vip-hcw7x                   0/1       CrashLoopBackOff   1          12s
kube-keepalived-vip-m5zdk                   0/1       CrashLoopBackOff   1          12s
kube-keepalived-vip-rkm7g                   0/1       CrashLoopBackOff   1          12s
nginx-ingress-controller-57f899f46f-mwknf   1/1       Running            1          8d

[root@master1 ~]# kubectl logs kube-keepalived-vip-hcw7x
F0118 11:22:15.920116       1 main.go:108] unexpected error: exit status 1
goroutine 1 [running]:
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.stacks(0xc42049cb00, 0xc4203bac80, 0x4b, 0x9d)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:766 +0xa7
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).output(0x1e2a9c0, 0xc400000003, 0xc4200904d0, 0x1d9086d, 0x7, 0x6c, 0x0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:717 +0x348
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).printf(0x1e2a9c0, 0xc400000003, 0x157a081, 0x14, 0xc420579ee8, 0x1, 0x1)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:655 +0x14f
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.Fatalf(0x157a081, 0x14, 0xc420579ee8, 0x1, 0x1)
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
        /usr/local/google/home/mikedanese/go/src/k8s.io/contrib/keepalived-vip/main.go:108 +0x32e
```

**Comment by hoanhdo** [comment]
@FNaughton   @grailsweb   you can fix it by 1 on 2 ways
1. add command 'modprobe ip_vs' to bashrc
2. load module on reboot.

**Comment by FNaughton** [comment]
@hoanhdo 
This is not working for me. I deleted the kube-keepalived-vip daemonset, rebooted the VM, ran modprobe ip_vs and then re-created the daemonset. Pods failed to start with the same error log.
Can you elaborate a little on why ip_vs module might be necessary?

**Comment by FNaughton** [comment]
Yes, this works for me now. I must have missed one of the nodes. The command must be run on all nodes..

**Comment by hoanhdo** [comment]
@FNaughton.
Great.
It need ip_vs module because kube-keepavlied use use ip_vs mode to create virtual interface.
You can see vip ip on ip -4 a command

**Comment by mrbobbytables** [comment]
If it helps, we solved this problem by adding a privileged initContainer that executed modprobe from a centos image before starting up the keepalived container itself:
```
initContainers:
- args:
  - ip_vs
  command:
  - modprobe
  image: centos:7
  imagePullPolicy: IfNotPresent
  name: kube-keepalived-vip-modprobe
  securityContext:
    privileged: true
  volumeMounts:
  - mountPath: /lib/modules
    name: modules
    readOnly: true
  - mountPath: /dev
    name: dev
```

**Comment by hoanhdo** [comment]
@mrbobbytables 
Good
I think it is best answer.

**Comment by RambleRainbow** [comment]
@mrbobbytables 
Very thanks.
I solved the problem
